[20170426-095138]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', modulo='P', dadoSincronizacao='dsadadasds', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-095138]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-095138]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-095138]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-095138]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-095138]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-095138]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-095138]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-095138]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-095138]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-095138]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-095138]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-095138]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-095138]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-095138]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-095138]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-095138]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-095138]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-095138]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-095138]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-095138]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-095138]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-095138]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-095138]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-095138]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-095138]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-095138]: 	at java.lang.Thread.run(Unknown Source)
[20170426-095138]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-095138]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:50)
[20170426-095138]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170426-095138]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:72)
[20170426-095138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-095138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-095138]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-095138]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-095138]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-095138]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-095138]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-095138]: 	... 29 more
[20170426-095138]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-095138]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-095138]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-095138]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-095138]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:41)
[20170426-095138]: 	... 38 more
[20170426-095138]: .
[20170426-100951]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='127.0.0.1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-100951]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-100951]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-100951]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-100951]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-100951]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-100951]: 	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:507)
[20170426-100951]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
[20170426-100951]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-100951]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-100951]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-100951]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-100951]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-100951]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-100951]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-100951]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-100951]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-100951]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-100951]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-100951]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-100951]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-100951]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-100951]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-100951]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-100951]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-100951]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-100951]: 	at java.lang.Thread.run(Unknown Source)
[20170426-100951]: Caused by: java.lang.NullPointerException
[20170426-100951]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:72)
[20170426-100951]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-100951]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-100951]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-100951]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-100951]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-100951]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-100951]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-100951]: 	... 29 more
[20170426-100951]: .
[20170426-101028]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='127.0.0.1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-101028]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-101028]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-101028]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-101028]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-101028]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-101028]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-101028]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-101028]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101028]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101028]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101028]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101028]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-101028]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-101028]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-101028]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-101028]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-101028]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-101028]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-101028]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-101028]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-101028]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-101028]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-101028]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-101028]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-101028]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-101028]: 	at java.lang.Thread.run(Unknown Source)
[20170426-101028]: Caused by: java.lang.NullPointerException
[20170426-101028]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:111)
[20170426-101028]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-101028]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-101028]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-101028]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-101028]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-101028]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-101028]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-101028]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-101028]: 	... 29 more
[20170426-101028]: .
[20170426-101231]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='127.0.0.1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='123123', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-101231]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-101231]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-101231]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-101231]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-101231]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-101231]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-101231]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-101231]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101231]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101231]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101231]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101231]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-101231]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-101231]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-101231]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-101231]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-101231]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-101231]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-101231]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-101231]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-101231]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-101231]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-101231]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-101231]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-101231]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-101231]: 	at java.lang.Thread.run(Unknown Source)
[20170426-101231]: Caused by: java.lang.NullPointerException
[20170426-101231]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:111)
[20170426-101231]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-101231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-101231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-101231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-101231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-101231]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-101231]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-101231]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-101231]: 	... 29 more
[20170426-101231]: .
[20170426-101332]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='127.0.0.1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', modulo='A', dadoSincronizacao='1231231231', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-101332]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-101332]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-101332]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-101332]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-101332]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-101332]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-101332]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-101332]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101332]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101332]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101332]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101332]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-101332]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-101332]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-101332]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-101332]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-101332]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-101332]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-101332]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-101332]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-101332]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-101332]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-101332]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-101332]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-101332]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-101332]: 	at java.lang.Thread.run(Unknown Source)
[20170426-101332]: Caused by: java.lang.NullPointerException
[20170426-101332]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:112)
[20170426-101332]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-101332]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-101332]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-101332]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-101332]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-101332]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-101332]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-101332]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-101332]: 	... 29 more
[20170426-101332]: .
[20170426-101455]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='127.0.0.1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='1231231231231', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-101455]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-101455]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-101455]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-101455]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-101455]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-101455]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-101455]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-101455]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101455]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101455]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-101455]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-101455]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-101455]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-101455]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-101455]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-101455]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-101455]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-101455]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-101455]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-101455]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-101455]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-101455]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-101455]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-101455]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-101455]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-101455]: 	at java.lang.Thread.run(Unknown Source)
[20170426-101455]: Caused by: java.lang.NullPointerException
[20170426-101455]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:112)
[20170426-101455]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-101455]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-101455]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-101455]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-101455]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-101455]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-101455]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-101455]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-101455]: 	... 29 more
[20170426-101455]: .
[20170426-102645]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='123123123', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170426-102645]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-102645]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-102645]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-102645]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-102645]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-102645]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-102645]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-102645]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102645]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102645]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-102645]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102645]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-102645]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-102645]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-102645]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-102645]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-102645]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-102645]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-102645]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-102645]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-102645]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-102645]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-102645]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-102645]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-102645]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-102645]: 	at java.lang.Thread.run(Unknown Source)
[20170426-102645]: Caused by: java.lang.NullPointerException
[20170426-102645]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:112)
[20170426-102645]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-102645]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-102645]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-102645]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-102645]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-102645]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-102645]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-102645]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-102645]: 	... 29 more
[20170426-102645]: .
[20170426-102725]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='P', dadoSincronizacao='01114444655', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-102725]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-102725]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-102725]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-102725]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-102725]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-102725]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-102725]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-102725]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102725]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102725]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-102725]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-102725]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-102725]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-102725]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-102725]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-102725]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-102725]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-102725]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-102725]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-102725]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-102725]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-102725]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-102725]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-102725]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-102725]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-102725]: 	at java.lang.Thread.run(Unknown Source)
[20170426-102725]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-102725]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:50)
[20170426-102725]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:109)
[20170426-102725]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170426-102725]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-102725]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-102725]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-102725]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-102725]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-102725]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-102725]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-102725]: 	... 29 more
[20170426-102725]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-102725]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-102725]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-102725]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-102725]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:41)
[20170426-102725]: 	... 38 more
[20170426-102725]: .
[20170426-103947]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='1231231231231', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-103947]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-103947]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-103947]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-103947]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-103947]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-103947]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-103947]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-103947]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-103947]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-103947]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-103947]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-103947]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-103947]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-103947]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-103947]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-103947]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-103947]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-103947]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-103947]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-103947]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-103947]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-103947]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-103947]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-103947]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-103947]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-103947]: 	at java.lang.Thread.run(Unknown Source)
[20170426-103947]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-103947]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-103947]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-103947]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-103947]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-103947]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-103947]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-103947]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-103947]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-103947]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-103947]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-103947]: 	... 29 more
[20170426-103947]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-103947]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-103947]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-103947]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-103947]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-103947]: 	... 38 more
[20170426-103947]: .
[20170426-104254]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='123121231231', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104254]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104254]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104254]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104254]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104254]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104254]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104254]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104254]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104254]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104254]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104254]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104254]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104254]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104254]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104254]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104254]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104254]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104254]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104254]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104254]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104254]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104254]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-104254]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104254]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104254]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104254]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104254]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104254]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-104254]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-104254]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-104254]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104254]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104254]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104254]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104254]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104254]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104254]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104254]: 	... 29 more
[20170426-104254]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104254]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104254]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104254]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104254]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-104254]: 	... 38 more
[20170426-104254]: .
[20170426-104336]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', modulo='A', dadoSincronizacao='1231231231231', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoFundo(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoFundo'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoFundo(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoFundo'.
[20170426-104336]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104336]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104336]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104336]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104336]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104336]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104336]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104336]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104336]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104336]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104336]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104336]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104336]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104336]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104336]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104336]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104336]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104336]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104336]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104336]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104336]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104336]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170426-104336]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104336]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104336]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104336]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104336]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoFundo(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoFundo'.
[20170426-104336]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-104336]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-104336]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-104336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104336]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104336]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104336]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104336]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104336]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104336]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104336]: 	... 29 more
[20170426-104336]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoFundo'.
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104336]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104336]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104336]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104336]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-104336]: 	... 38 more
[20170426-104336]: .
[20170426-104417]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='12123123', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104417]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104417]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104417]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104417]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104417]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104417]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104417]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104417]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104417]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104417]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104417]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104417]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104417]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104417]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104417]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104417]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104417]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104417]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104417]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104417]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104417]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104417]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-104417]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104417]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104417]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104417]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104417]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104417]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-104417]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-104417]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-104417]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104417]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104417]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104417]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104417]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104417]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104417]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104417]: 	... 29 more
[20170426-104417]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104417]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104417]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104417]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104417]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-104417]: 	... 38 more
[20170426-104417]: .
[20170426-104438]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='12123123123123123', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104438]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104438]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104438]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104438]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104438]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104438]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104438]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104438]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104438]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104438]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104438]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104438]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104438]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104438]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104438]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104438]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104438]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104438]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104438]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104438]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104438]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104438]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-104438]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104438]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104438]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104438]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104438]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104438]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-104438]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-104438]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-104438]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104438]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104438]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104438]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104438]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104438]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104438]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104438]: 	... 29 more
[20170426-104438]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104438]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104438]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104438]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104438]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-104438]: 	... 38 more
[20170426-104438]: .
[20170426-104504]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='P', dadoSincronizacao='123123123123', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-104504]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104504]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104504]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104504]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104504]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104504]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104504]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104504]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104504]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104504]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104504]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104504]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104504]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104504]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104504]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104504]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104504]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104504]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104504]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104504]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104504]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104504]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-104504]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104504]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104504]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104504]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104504]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170426-104504]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:50)
[20170426-104504]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:110)
[20170426-104504]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170426-104504]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104504]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104504]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104504]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104504]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104504]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104504]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104504]: 	... 29 more
[20170426-104504]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104504]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104504]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104504]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104504]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:41)
[20170426-104504]: 	... 38 more
[20170426-104504]: .
[20170426-104634]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', modulo='A', dadoSincronizacao='1212312312313', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104634]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170426-104634]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170426-104634]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170426-104634]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170426-104634]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170426-104634]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170426-104634]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170426-104634]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104634]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104634]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170426-104634]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170426-104634]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170426-104634]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170426-104634]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170426-104634]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170426-104634]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170426-104634]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170426-104634]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170426-104634]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170426-104634]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170426-104634]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170426-104634]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170426-104634]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20170426-104634]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20170426-104634]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170426-104634]: 	at java.lang.Thread.run(Unknown Source)
[20170426-104634]: Caused by: util.BancoDadosException: QUERY: {CALL adm.pOrquestAtvoEmpr(?)} ERRO: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104634]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:41)
[20170426-104634]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizarAtivo(ConteudoMenuEntity.java:113)
[20170426-104634]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170426-104634]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170426-104634]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20170426-104634]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20170426-104634]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20170426-104634]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170426-104634]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170426-104634]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170426-104634]: 	... 29 more
[20170426-104634]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'adm.pOrquestAtvoEmpr'.
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170426-104634]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170426-104634]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104634]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170426-104634]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoAtivosSQLDAO.sincronizar(SincronizacaoAtivosSQLDAO.java:32)
[20170426-104634]: 	... 38 more
[20170426-104634]: .
