[20170310-130031]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/ConfirmarLogo.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, tipoSincronizacao='', dadoSincronizacao='', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170310-130031]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170310-130031]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170310-130031]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170310-130031]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170310-130031]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170310-130031]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170310-130031]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170310-130031]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170310-130031]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170310-130031]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-130031]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170310-130031]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170310-130031]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-130031]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170310-130031]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170310-130031]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170310-130031]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170310-130031]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170310-130031]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170310-130031]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170310-130031]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170310-130031]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170310-130031]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170310-130031]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170310-130031]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170310-130031]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170310-130031]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170310-130031]: 	at java.lang.Thread.run(Thread.java:662)
[20170310-130031]: Caused by: java.lang.NullPointerException
[20170310-130031]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.ConfirmarLogoAction.executeAction(ConfirmarLogoAction.java:53)
[20170310-130031]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.AdministracaoBaseAction.execute(AdministracaoBaseAction.java:38)
[20170310-130031]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170310-130031]: 	... 26 more
[20170310-130031]: .
[20170310-131024]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/ConfirmarLogo.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170310-131024]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170310-131024]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170310-131024]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170310-131024]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170310-131024]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170310-131024]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170310-131024]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170310-131024]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170310-131024]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170310-131024]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131024]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170310-131024]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170310-131024]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131024]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170310-131024]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170310-131024]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170310-131024]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170310-131024]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170310-131024]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170310-131024]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170310-131024]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170310-131024]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170310-131024]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170310-131024]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170310-131024]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170310-131024]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170310-131024]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170310-131024]: 	at java.lang.Thread.run(Thread.java:662)
[20170310-131024]: Caused by: java.lang.NullPointerException
[20170310-131024]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.ConfirmarLogoAction.executeAction(ConfirmarLogoAction.java:53)
[20170310-131024]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.AdministracaoBaseAction.execute(AdministracaoBaseAction.java:38)
[20170310-131024]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170310-131024]: 	... 26 more
[20170310-131024]: .
[20170310-131045]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/ConfirmarLogo.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170310-131045]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170310-131045]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170310-131045]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170310-131045]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170310-131045]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170310-131045]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170310-131045]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170310-131045]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170310-131045]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170310-131045]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131045]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170310-131045]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170310-131045]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131045]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170310-131045]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170310-131045]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170310-131045]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170310-131045]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170310-131045]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170310-131045]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170310-131045]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170310-131045]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170310-131045]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170310-131045]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170310-131045]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170310-131045]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170310-131045]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170310-131045]: 	at java.lang.Thread.run(Thread.java:662)
[20170310-131045]: Caused by: java.lang.NullPointerException
[20170310-131045]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.ConfirmarLogoAction.executeAction(ConfirmarLogoAction.java:53)
[20170310-131045]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.AdministracaoBaseAction.execute(AdministracaoBaseAction.java:38)
[20170310-131045]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170310-131045]: 	... 26 more
[20170310-131045]: .
[20170310-131258]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/ConfirmarLogo.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170310-131258]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170310-131258]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170310-131258]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170310-131258]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170310-131258]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170310-131258]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170310-131258]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170310-131258]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170310-131258]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170310-131258]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131258]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170310-131258]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170310-131258]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-131258]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170310-131258]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170310-131258]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170310-131258]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170310-131258]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170310-131258]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170310-131258]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170310-131258]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170310-131258]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170310-131258]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170310-131258]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170310-131258]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170310-131258]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170310-131258]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170310-131258]: 	at java.lang.Thread.run(Thread.java:662)
[20170310-131258]: Caused by: java.lang.NullPointerException
[20170310-131258]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.ConfirmarLogoAction.executeAction(ConfirmarLogoAction.java:53)
[20170310-131258]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.AdministracaoBaseAction.execute(AdministracaoBaseAction.java:38)
[20170310-131258]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170310-131258]: 	... 26 more
[20170310-131258]: .
[20170310-135919]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170310-135919]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170310-135919]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170310-135919]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170310-135919]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170310-135919]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170310-135919]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170310-135919]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170310-135919]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170310-135919]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170310-135919]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-135919]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170310-135919]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170310-135919]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170310-135919]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170310-135919]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170310-135919]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170310-135919]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170310-135919]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170310-135919]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170310-135919]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170310-135919]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170310-135919]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170310-135919]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170310-135919]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170310-135919]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170310-135919]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170310-135919]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170310-135919]: 	at java.lang.Thread.run(Thread.java:662)
[20170310-135919]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170310-135919]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:47)
[20170310-135919]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170310-135919]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170310-135919]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170310-135919]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170310-135919]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170310-135919]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170310-135919]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170310-135919]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170310-135919]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170310-135919]: 	... 26 more
[20170310-135919]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170310-135919]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170310-135919]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170310-135919]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170310-135919]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170310-135919]: 	... 35 more
[20170310-135919]: .
