[20170314-083204]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-083204]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-083204]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-083204]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-083204]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-083204]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-083204]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-083204]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-083204]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-083204]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-083204]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083204]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-083204]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-083204]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083204]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-083204]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-083204]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-083204]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-083204]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-083204]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-083204]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-083204]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-083204]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-083204]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-083204]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-083204]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-083204]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-083204]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-083204]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-083204]: Caused by: java.lang.NullPointerException
[20170314-083204]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-083204]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-083204]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-083204]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-083204]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-083204]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-083204]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-083204]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-083204]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-083204]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-083204]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-083204]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:36)
[20170314-083204]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-083204]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-083204]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-083204]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-083204]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-083204]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-083204]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-083204]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-083204]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-083204]: 	... 26 more
[20170314-083204]: .
[20170314-083305]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-083305]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-083305]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-083305]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-083305]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-083305]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-083305]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-083305]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-083305]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-083305]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-083305]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083305]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-083305]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-083305]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083305]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-083305]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-083305]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-083305]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-083305]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-083305]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-083305]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-083305]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-083305]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-083305]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-083305]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-083305]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-083305]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-083305]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-083305]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-083305]: Caused by: java.lang.NullPointerException
[20170314-083305]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-083305]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-083305]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-083305]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-083305]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-083305]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-083305]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-083305]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-083305]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-083305]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-083305]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-083305]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:36)
[20170314-083305]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-083305]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-083305]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-083305]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-083305]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-083305]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-083305]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-083305]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-083305]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-083305]: 	... 26 more
[20170314-083305]: .
[20170314-083452]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-083452]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-083452]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-083452]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-083452]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-083452]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-083452]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-083452]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-083452]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-083452]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-083452]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083452]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-083452]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-083452]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-083452]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-083452]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-083452]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-083452]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-083452]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-083452]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-083452]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-083452]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-083452]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-083452]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-083452]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170314-083452]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-083452]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-083452]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-083452]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-083452]: Caused by: java.lang.NullPointerException
[20170314-083452]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-083452]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-083452]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-083452]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-083452]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-083452]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-083452]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-083452]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-083452]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-083452]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-083452]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-083452]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:36)
[20170314-083452]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-083452]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-083452]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-083452]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-083452]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-083452]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-083452]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-083452]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-083452]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-083452]: 	... 26 more
[20170314-083452]: .
[20170314-084030]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-084030]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-084030]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-084030]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-084030]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-084030]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-084030]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-084030]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-084030]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-084030]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-084030]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-084030]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-084030]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-084030]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-084030]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-084030]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-084030]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-084030]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-084030]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-084030]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-084030]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-084030]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-084030]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-084030]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-084030]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170314-084030]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-084030]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-084030]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-084030]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-084030]: Caused by: java.lang.NullPointerException
[20170314-084030]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-084030]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-084030]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-084030]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-084030]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-084030]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-084030]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-084030]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-084030]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-084030]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-084030]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-084030]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:36)
[20170314-084030]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-084030]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-084030]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-084030]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-084030]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-084030]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-084030]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-084030]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-084030]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-084030]: 	... 26 more
[20170314-084030]: .
[20170314-085418]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-085418]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-085418]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-085418]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-085418]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-085418]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-085418]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-085418]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-085418]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-085418]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-085418]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-085418]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-085418]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-085418]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-085418]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-085418]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-085418]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-085418]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-085418]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-085418]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-085418]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-085418]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-085418]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-085418]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-085418]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170314-085418]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-085418]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-085418]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-085418]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-085418]: Caused by: java.lang.NullPointerException
[20170314-085418]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-085418]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-085418]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-085418]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-085418]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-085418]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-085418]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-085418]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-085418]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-085418]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-085418]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-085418]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:37)
[20170314-085418]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-085418]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-085418]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-085418]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-085418]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-085418]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-085418]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-085418]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-085418]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-085418]: 	... 26 more
[20170314-085418]: .
[20170314-090202]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-090202]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-090202]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-090202]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-090202]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-090202]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-090202]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-090202]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-090202]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-090202]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-090202]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090202]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-090202]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-090202]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090202]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-090202]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-090202]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-090202]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-090202]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-090202]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-090202]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-090202]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-090202]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-090202]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-090202]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-090202]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-090202]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-090202]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-090202]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-090202]: Caused by: java.lang.NullPointerException
[20170314-090202]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-090202]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-090202]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-090202]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-090202]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-090202]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-090202]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-090202]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-090202]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-090202]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-090202]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-090202]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:37)
[20170314-090202]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-090202]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-090202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-090202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-090202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-090202]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-090202]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-090202]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-090202]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-090202]: 	... 26 more
[20170314-090202]: .
[20170314-090317]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-090317]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-090317]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-090317]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-090317]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-090317]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-090317]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-090317]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-090317]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-090317]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-090317]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090317]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-090317]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-090317]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090317]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-090317]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-090317]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-090317]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-090317]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-090317]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-090317]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-090317]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-090317]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-090317]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-090317]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-090317]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-090317]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-090317]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-090317]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-090317]: Caused by: java.lang.NullPointerException
[20170314-090317]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-090317]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-090317]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-090317]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-090317]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-090317]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-090317]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-090317]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-090317]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-090317]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-090317]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-090317]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:42)
[20170314-090317]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-090317]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-090317]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-090317]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-090317]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-090317]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-090317]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-090317]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-090317]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-090317]: 	... 26 more
[20170314-090317]: .
[20170314-090418]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-090418]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-090418]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-090418]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-090418]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-090418]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-090418]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-090418]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-090418]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-090418]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-090418]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090418]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-090418]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-090418]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090418]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-090418]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-090418]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-090418]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-090418]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-090418]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-090418]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-090418]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-090418]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-090418]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-090418]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-090418]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-090418]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-090418]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-090418]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-090418]: Caused by: java.lang.NullPointerException
[20170314-090418]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-090418]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-090418]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-090418]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-090418]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-090418]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-090418]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-090418]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-090418]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-090418]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-090418]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-090418]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:42)
[20170314-090418]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-090418]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-090418]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-090418]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-090418]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-090418]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-090418]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-090418]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-090418]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-090418]: 	... 26 more
[20170314-090418]: .
[20170314-090448]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-090448]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-090448]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-090448]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-090448]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-090448]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-090448]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-090448]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-090448]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-090448]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-090448]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090448]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-090448]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-090448]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090448]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-090448]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-090448]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-090448]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-090448]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-090448]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-090448]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-090448]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-090448]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-090448]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-090448]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-090448]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-090448]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-090448]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-090448]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-090448]: Caused by: java.lang.NullPointerException
[20170314-090448]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-090448]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-090448]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-090448]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-090448]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-090448]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-090448]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-090448]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-090448]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-090448]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-090448]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-090448]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:42)
[20170314-090448]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-090448]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-090448]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-090448]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-090448]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-090448]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-090448]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-090448]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-090448]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-090448]: 	... 26 more
[20170314-090448]: .
[20170314-090619]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='', dadoSincronizacao='123456', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-090619]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-090619]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-090619]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-090619]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-090619]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-090619]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-090619]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-090619]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-090619]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-090619]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090619]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-090619]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-090619]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-090619]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-090619]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-090619]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-090619]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-090619]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-090619]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-090619]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-090619]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-090619]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-090619]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-090619]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170314-090619]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-090619]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-090619]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-090619]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-090619]: Caused by: java.lang.NullPointerException
[20170314-090619]: 	at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
[20170314-090619]: 	at java.util.regex.Matcher.reset(Matcher.java:291)
[20170314-090619]: 	at java.util.regex.Matcher.<init>(Matcher.java:211)
[20170314-090619]: 	at java.util.regex.Pattern.matcher(Pattern.java:888)
[20170314-090619]: 	at com.microsoft.sqlserver.jdbc.JDBCCallSyntaxTranslator.translate(SQLServerStatement.java:2275)
[20170314-090619]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.<init>(SQLServerPreparedStatement.java:93)
[20170314-090619]: 	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.<init>(SQLServerCallableStatement.java:63)
[20170314-090619]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:2177)
[20170314-090619]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareCall(SQLServerConnection.java:1861)
[20170314-090619]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.prepareCall(DelegatingConnection.java:308)
[20170314-090619]: 	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareCall(PoolingDataSource.java:303)
[20170314-090619]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:42)
[20170314-090619]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-090619]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170314-090619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-090619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-090619]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-090619]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-090619]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-090619]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-090619]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-090619]: 	... 26 more
[20170314-090619]: .
[20170314-121202]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170314-121202]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-121202]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-121202]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-121202]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-121202]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-121202]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-121202]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-121202]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-121202]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-121202]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-121202]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-121202]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-121202]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-121202]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-121202]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-121202]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-121202]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-121202]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-121202]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-121202]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-121202]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-121202]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-121202]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-121202]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-121202]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-121202]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-121202]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-121202]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-121202]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170314-121202]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:50)
[20170314-121202]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170314-121202]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:73)
[20170314-121202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170314-121202]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170314-121202]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170314-121202]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170314-121202]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170314-121202]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170314-121202]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-121202]: 	... 26 more
[20170314-121202]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170314-121202]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170314-121202]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170314-121202]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170314-121202]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:41)
[20170314-121202]: 	... 35 more
[20170314-121202]: .
[20170314-125126]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/IncluirCampanhaEntrada.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='1', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125126]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125126]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125126]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125126]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125126]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125126]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125126]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125126]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125126]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125126]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125126]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125126]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125126]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125126]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125126]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125126]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125126]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125126]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125126]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125126]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125126]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125126]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125126]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125126]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125126]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125126]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125126]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125126]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125126]: Caused by: java.lang.NullPointerException
[20170314-125126]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125126]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125126]: 	... 26 more
[20170314-125126]: .
[20170314-125129]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/ConsultarCampanha.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='1', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125129]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125129]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125129]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125129]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125129]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125129]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125129]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125129]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125129]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125129]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125129]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125129]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125129]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125129]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125129]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125129]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125129]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125129]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125129]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125129]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125129]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125129]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125129]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125129]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125129]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125129]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125129]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125129]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125129]: Caused by: java.lang.NullPointerException
[20170314-125129]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125129]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125129]: 	... 26 more
[20170314-125129]: .
[20170314-125133]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/ConsultarCampanha.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='2', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125133]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125133]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125133]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125133]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125133]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125133]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125133]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125133]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125133]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125133]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125133]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125133]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125133]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125133]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125133]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125133]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125133]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125133]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125133]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125133]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125133]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125133]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125133]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125133]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125133]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125133]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125133]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125133]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125133]: Caused by: java.lang.NullPointerException
[20170314-125133]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125133]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125133]: 	... 26 more
[20170314-125133]: .
[20170314-125243]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/IncluirCampanhaEntrada.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='2', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125243]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125243]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125243]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125243]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125243]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125243]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125243]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125243]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125243]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125243]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125243]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125243]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125243]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125243]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125243]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125243]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125243]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125243]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125243]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125243]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125243]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125243]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125243]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125243]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170314-125243]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125243]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125243]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125243]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125243]: Caused by: java.lang.NullPointerException
[20170314-125243]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125243]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125243]: 	... 26 more
[20170314-125243]: .
[20170314-125245]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/ConsultarCampanha.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='2', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125245]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125245]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125245]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125245]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125245]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125245]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125245]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125245]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125245]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125245]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125245]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125245]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125245]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125245]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125245]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125245]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125245]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125245]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125245]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125245]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125245]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125245]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125245]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125245]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125245]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125245]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125245]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125245]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125245]: Caused by: java.lang.NullPointerException
[20170314-125245]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125245]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125245]: 	... 26 more
[20170314-125245]: .
[20170314-125248]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/IncluirCampanhaEntrada.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='1', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125248]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125248]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125248]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125248]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125248]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125248]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125248]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125248]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125248]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125248]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125248]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125248]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125248]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125248]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125248]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125248]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125248]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125248]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125248]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125248]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125248]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125248]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125248]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125248]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125248]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125248]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125248]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125248]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125248]: Caused by: java.lang.NullPointerException
[20170314-125248]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125248]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125248]: 	... 26 more
[20170314-125248]: .
[20170314-125249]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipacampanhas', URI='/calipacampanhas/ConsultarCampanha.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, CTRL='null', cdAmbienteInternet='1', campanha.cdCategoriaPagina='1', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170314-125249]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170314-125249]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170314-125249]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170314-125249]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170314-125249]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170314-125249]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170314-125249]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170314-125249]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170314-125249]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170314-125249]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125249]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170314-125249]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170314-125249]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170314-125249]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170314-125249]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170314-125249]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170314-125249]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170314-125249]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170314-125249]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170314-125249]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170314-125249]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170314-125249]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170314-125249]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170314-125249]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170314-125249]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170314-125249]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170314-125249]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170314-125249]: 	at java.lang.Thread.run(Thread.java:662)
[20170314-125249]: Caused by: java.lang.NullPointerException
[20170314-125249]: 	at br.com.bradesco.custodia.portal.campanhas.apresentacao.CampanhasBaseAction.execute(CampanhasBaseAction.java:114)
[20170314-125249]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170314-125249]: 	... 26 more
[20170314-125249]: .
